<?php

return [
    'vector_installed' => env('VECTOR_INSTALLED', true),
    'api_url' => env('VECTOR_API_URL', null),
    'api_key' => env('VECTOR_API_KEY', null),
    'agent_source_dns_ttl_seconds' => env('VECTOR_AGENT_SOURCE_DNS_TTL_SECONDS', 300),
    // Must exceed the longest possible legitimate job runtime (template timeout * retry_count).
    // Default covers the built-in 30s timeout × 3 retries with headroom.
    // Increase if templates use high timeouts (e.g. 120s × 3 retries ≈ 6 min → set to 15+).
    'stale_job_timeout_minutes' => env('VECTOR_STALE_JOB_TIMEOUT_MINUTES', 10),

    // Vector Hub (RCO-744 live channel). Unset hub.api_url disables the
    // integration entirely; nothing that works today depends on it.
    'hub' => [
        // Delivered to agents in the sync payload; agents dial this.
        'tunnel_url' => env('VECTOR_HUB_TUNNEL_URL', null), // e.g. wss://rconfig.local:8443/tunnel
        // Laravel -> hub control API (loopback, mTLS in production).
        'api_url' => env('VECTOR_HUB_API_URL', null), // e.g. https://127.0.0.1:8444
        // Laravel -> hub session broker (loopback) for interactive device
        // sessions via `php artisan vector:ssh` (RCO-1155).
        'session_addr' => env('VECTOR_HUB_SESSION_ADDR', null), // e.g. 127.0.0.1:8445
        // Shared secret the hub presents when calling back into Laravel
        // (token -> agent id resolution). Generated by the install script.
        'auth_secret' => env('VECTOR_HUB_AUTH_SECRET', null),
        // mTLS client credentials for Laravel -> hub calls.
        'client_cert' => env('VECTOR_HUB_CLIENT_CERT', null),
        'client_key' => env('VECTOR_HUB_CLIENT_KEY', null),
        'ca_cert' => env('VECTOR_HUB_CA_CERT', null),
        // Installed hub binary; its presence is how the UI detects an install.
        'bin_path' => env('VECTOR_HUB_BIN_PATH', '/usr/local/bin/rconfig/activehub/vector-hub'),
        // Root-owned dir the install writes the hub's TLS material to; the
        // client-cert self-heal (SyncHubCertsJob) re-copies from here.
        'tls_source_dir' => env('VECTOR_HUB_TLS_SOURCE_DIR', '/etc/vector-hub/tls'),
    ],
];
